/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fenomenotransporte;

import javax.swing.JFrame;

/**
 *
 * @author peterpc
 */
public class menu extends javax.swing.JFrame {

    public double  L, gamma_liquido, h; //altura, Pespecifico e comprimento
    public double b, FH, P, Ycp; //largura base, força hidrostatica, peso parede, ponto aplicacao de Fh 
    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    //setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pontosAp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txth = new javax.swing.JTextField();
        txtL = new javax.swing.JTextField();
        txtGama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFh = new javax.swing.JLabel();
        txtFp = new javax.swing.JLabel();
        txtYcp = new javax.swing.JLabel();
        txtB = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bcalc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pontosAp.setBackground(new java.awt.Color(255, 255, 255));
        pontosAp.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        pontosAp.setText("h(altura da parede e líquido) X Pontos de Aplicação");
        pontosAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontosApActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("GRÁFICOS");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jButton1.setText("Peso Específico do Líquido X largura da base da parede");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jButton2.setText("h(altura da parede e líquido X largura da base da parede");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jButton3.setText("h(altura da parede) X Fh (Intensidade da força)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jButton4.setText("Peso Específico do líquido X Intensidade da força");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jButton5.setText("Comprimento L da parede X Intensidade da força");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(pontosAp))
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(pontosAp)
                .addGap(21, 21, 21))
        );

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel3.setText("ENTRADAS");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel4.setText("Altura h da parede/líquido (m):");

        jLabel5.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel5.setText("Comprimento L da parede (m):");

        jLabel6.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel6.setText("Peso Específco do líquido (kN/m^3):");

        txtFh.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txtFh.setText("Intensidade da Força Hidrostática (kN): ");

        txtFp.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txtFp.setText("Peso da Parede (kN): ");

        txtYcp.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txtYcp.setText("Altura do Ponto de Aplicação da Força Hidrostática (m):");

        txtB.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        txtB.setText("Largura mínima da base da parede (m):");

        jLabel9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel9.setText("RESULTADOS");

        bcalc.setBackground(new java.awt.Color(255, 255, 255));
        bcalc.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        bcalc.setText("Calcular");
        bcalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(142, 142, 142))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGama, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txth, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtYcp)
                            .addComponent(txtB)
                            .addComponent(txtFh)
                            .addComponent(txtFp)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bcalc)
                                    .addComponent(jLabel9)))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtGama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bcalc)
                .addGap(18, 18, 18)
                .addComponent(txtB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtYcp)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(274, 274, 274))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pontosApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontosApActionPerformed
              // coletando dados fornecidos pelo usuário
        String altura = txth.getText();
        String peso_esp = txtGama.getText();
        String comprimento = txtL.getText();
        //fazendo parsing dos dados
        h = Double.parseDouble(altura);
        gamma_liquido = Double.parseDouble(peso_esp);
        L = Double.parseDouble(comprimento);
        
        tela nova = new tela(L, gamma_liquido, h, 2); //opcao 2 = alturaXpontosAplcicacao
        nova.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       nova.setVisible(true);
        
    }//GEN-LAST:event_pontosApActionPerformed

    private void bcalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcalcActionPerformed
        // coletando dados fornecidos pelo usuário
        String altura = txth.getText();
        String peso_esp = txtGama.getText();
        String comprimento = txtL.getText();
        //fazendo parsing dos dados
        h = Double.parseDouble(altura);
        gamma_liquido = Double.parseDouble(peso_esp);
        L = Double.parseDouble(comprimento);
        
        //calculando saídas:
        CalculaResultados calc = new CalculaResultados();
        b = calc.LarguraBase(gamma_liquido, h);
        FH = calc.IntensidadeForca(gamma_liquido, h, L);
        Ycp = calc.PontoDeAplicacao(h, L);
        P = calc.PesoParede(b, h, L);
        
        //escrevendo saidas
        txtB.setText("Largura mínima da base da parede (m): "+String.format("%.2f",b));
        txtFh.setText("Intensidade da Força Hidrostática (kN): "+String.format("%.2f",FH));
        txtFp.setText("Peso da Parede (kN): "+String.format("%.2f",P));
        txtYcp.setText("Altura do Ponto de Aplicação da Força Hidrostática (m): "+ String.format("%.2f",Ycp));
    }//GEN-LAST:event_bcalcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // coletando dados fornecidos pelo usuário
        String altura = txth.getText();
        String peso_esp = txtGama.getText();
        String comprimento = txtL.getText();
        //fazendo parsing dos dados
        h = Double.parseDouble(altura);
        gamma_liquido = Double.parseDouble(peso_esp);
        L = Double.parseDouble(comprimento);
        
        tela nova = new tela(L, gamma_liquido, h, 3); //opcao 2 = gamma_liquidoXbase
        nova.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       nova.setVisible(true);
            }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              // coletando dados fornecidos pelo usuário
        String altura = txth.getText();
        String peso_esp = txtGama.getText();
        String comprimento = txtL.getText();
        //fazendo parsing dos dados
        h = Double.parseDouble(altura);
        gamma_liquido = Double.parseDouble(peso_esp);
        L = Double.parseDouble(comprimento);
        
        tela nova = new tela(L, gamma_liquido, h, 1); //opcao 1 = hXbase
        nova.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       nova.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             // coletando dados fornecidos pelo usuário
        String altura = txth.getText();
        String peso_esp = txtGama.getText();
        String comprimento = txtL.getText();
        //fazendo parsing dos dados
        h = Double.parseDouble(altura);
        gamma_liquido = Double.parseDouble(peso_esp);
        L = Double.parseDouble(comprimento);
        
        tela nova = new tela(L, gamma_liquido, h, 6); //opcao 6 = hXFh
        nova.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       nova.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
             // coletando dados fornecidos pelo usuário
        String altura = txth.getText();
        String peso_esp = txtGama.getText();
        String comprimento = txtL.getText();
        //fazendo parsing dos dados
        h = Double.parseDouble(altura);
        gamma_liquido = Double.parseDouble(peso_esp);
        L = Double.parseDouble(comprimento);
        
        tela nova = new tela(L, gamma_liquido, h, 4); //opcao 4 = gammaXForça
        nova.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       nova.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
             // coletando dados fornecidos pelo usuário
        String altura = txth.getText();
        String peso_esp = txtGama.getText();
        String comprimento = txtL.getText();
        //fazendo parsing dos dados
        h = Double.parseDouble(altura);
        gamma_liquido = Double.parseDouble(peso_esp);
        L = Double.parseDouble(comprimento);
        
        tela nova = new tela(L, gamma_liquido, h, 5); //opcao 5 = LXForca
        nova.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
       nova.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    
    //calcula ponto de aplicação da força
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcalc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton pontosAp;
    private javax.swing.JLabel txtB;
    private javax.swing.JLabel txtFh;
    private javax.swing.JLabel txtFp;
    private javax.swing.JTextField txtGama;
    private javax.swing.JTextField txtL;
    private javax.swing.JLabel txtYcp;
    private javax.swing.JTextField txth;
    // End of variables declaration//GEN-END:variables
}
